### ISSUE TITLE
barcheck fail: note crosses barline

### ISSUE THREAD

**Issue by suntong** [ssb22/jianpu-ly#19]
Please take a look at the change of 
https://github.com/suntong/jianpu/commit/2e42ae6561e001ec1c719b2ef76b4af693a8b4f0

for the song of  
https://github.com/suntong/jianpu/blob/master/mmd-木棉道.png

That extra leading `4/4,4` is causing the following error for me:

```
Error: (notesHad=5 5 6 5 3 2 3 3 2 1 2 3 2 1 6 6 6 1 3 2 - 2 0 5 5 6 5 3 2 3 3 2 1 2 3 2 1 6 3 2 3 2 1 - 1 0 1 2 1 7 6 5 6 6 5 3 3 3 4 4) barcheck fail: note crosses barline at "4" with 1 beams (12 skipped from 60 to 72, bypassing 64), scoreNo=1 barNo=11 (but the error could be earlier)
```

I'm wondering what the above error actually means, and why removing the leading `4/4,4` fixed the problem. thx.

**Comment by ssb22** [comment]
Hi, it's because the `,4` part of `4/4,4` means there's a 弱起拍 (anacrusis, pick-up) before the start, but 《木棉道》 has no 弱起拍 before the start.

Please may I ask, did you read something in the instructions that made you think you had to write `4/4,4` at the start of 《木棉道》?  Can you remember exactly what you read that made you think you had to do this?  so I can fix it :) thanks

**Comment by suntong** [comment]
Oh, I got it!! 

The following of the two songs has such `4/4,4` 

- https://github.com/suntong/jianpu/blob/master/Friends-朋友.jp
- https://github.com/suntong/jianpu/blob/master/yxdcb-隱形的翅膀.jp

and I wasn't sure why until seeing your kind explanation. 

I totally get it now. Thanks a lot!
