### ISSUE TITLE
The Underline Placement

### ISSUE THREAD

**Issue by suntong** [ssb22/jianpu-ly#20]
This might very well not [jianpu-ly](https://github.com/ssb22/jianpu-ly)'s problem, but take a look at this:

```
2/4
q2'. ( s3' ) s1' ( s6 q5 )
s6  q1' s6 s3'. d3' s3' s2' s1'. d1' q6 5
```

which would generate jianpu like this:

![image](https://user-images.githubusercontent.com/422244/226152104-1bab36db-b18b-49a5-a561-db73ed4151f2.png)

This is untraditional. 

The first verse is take from the JianPu bible (p2, 1st line):

https://musescore.org/sites/musescore.org/files/JianPu%20%5BMusic%20Editor%20Manual%5D.pdf

in which it should looks like:

![image](https://user-images.githubusercontent.com/422244/226152031-8219a306-c920-4fca-a21e-bd316e102ef0.png)

I.e., 

- the longer the underline is, the higher it should be placed
- the shorter the underline is, the lower it should be placed

I.e., the underline order should be reversed.

I don't know if [jianpu-ly](https://github.com/ssb22/jianpu-ly) can control lilypond output like above or not, if not, please passed on this bug report to them as your opinion should be a thousand times louder than mine. Thanks.

**Comment by ssb22** [comment]
The whole of jianpu-ly is a "hack" because it hasn't yet been possible to integrate Jianpu with Lilypond "properly", like guitar tablature and fingering diagrams are now integrated into Lilypond.  I hope eventually that Lilypond will be able to support Jianpu "natively" and you'll simply be able to ask for your music to be copied to a JianpuStaff like you can now use TabStaff.   (I hope Lilypond will have better support for Braille music too.) 
 Unfortunately I don't have any special way to supercharge the powers of the Lilypond core development team, nor can I afford a decent-sized payment into their bounty scheme.  David Zhang's [jianpu10a.ly](https://github.com/nybbs2003/lilypond-Jianpu/blob/master/jianpu10a.ly) goes some way toward proper JianpuStaff support but it's still limited.  Meanwhile, jianpu-ly's approach is to "hack" the appearance of Lilypond's Western 五线谱 staff to make ut

**Comment by ssb22** [comment]
The whole of jianpu-ly is a "hack" because it hasn't yet been possible to integrate Jianpu with Lilypond "properly", like guitar tablature and fingering diagrams are now integrated into Lilypond.  I hope eventually that Lilypond will be able to support Jianpu "natively" and you'll simply be able to ask for your music to be copied to a JianpuStaff like you can now use TabStaff.   (I hope Lilypond will have better support for Braille music too.) 
 Unfortunately I don't have any special way to supercharge the powers of the Lilypond core development team, nor can I afford a decent-sized payment into their bounty scheme.  David Zhang's [jianpu10a.ly](https://github.com/nybbs2003/lilypond-Jianpu/blob/master/jianpu10a.ly) goes some way toward proper JianpuStaff support but it's still limited.

Meanwhile, jianpu-ly's approach is to "hack" the appearance of Lilypond's Western 五线谱 staff to make it look like jianpu.  Delete the 5 staff lines.  Put all the notes on one line.  Change the shape of the note heads into numbers.  Delete the stems.  Make the beams thinner and closer to the notes.  That sort of thing.

What I've not yet figured out how to do is make the inner beams go in the "wrong" (from Lilypond's 五线谱 point of view) direction.  That's what would be needed to fix this issue.  I did try before, but I couldn't figure it out so eventually I just thought "won't fix".  I hope this script is still good enough, and I hope if lots of people use it, that might eventually encourage Lilypond developers to support Jianpu properly and then we won't need these "hacks" anymore.  I suppose we could try asking the core developers to give us a way to make beams look "inside-out", but I'd much rather if they could take the whole of Jianpu out of my hands entirely😊

**Comment by suntong** [comment]
Alright, got it 😭😭😭
Thanks for all the efforts you tried though ❤️❤️
