### ISSUE TITLE
Interview Request

### ISSUE THREAD

**Issue by suntong** [ssb22/jianpu-ly#25]
This might be the oddest issue I've ever raised, and I can anticipate that the answer would normally be "No", but still, I'd like to try at least, so that when the time comes, at least I can tell people that "I had tried my best". So before asking for it directly and getting a “No” as the answer, let me start with something else, to pave my way to my questions.

I live in Canada, Toronto. One year, I was on my way to see the autumn maple leaves and was a bit lost, so I drove around the vast mostly-empty area until I was able to see a small shop, and I went in to ask for directions. I said “I’m a bit lost”, and before I was able to explain anything else, the shop owner asked me if I was there to see the “Bethune House”. Not knowing anything about this Bethune House, and having great difficulties to communicate with the heavily accented shop owner, I basically came out of the shop “empty handed”. 

It was not until two or three years later when I heard that phrase “Bethune House” again, but this time it was from a Chinese person and I suddenly realized what it was, and I regret to have missed it ever since then, even until today. Yes, if you know what Bethune House is, it IS the Bethune Memorial House National Historic Site in Gravenhurst, Ontario, in memory and commemorates the life and achievements of Dr. Norman Bethune.

It’s in such a rural and remote area, which took me more than two and half hours to drive to get there, one won’t expect too much tourism traffic normally. Yet, Chinese from all over the world visit it, to pay their respects to Dr. Norman Bethune (and I will too sometime in future). So from that small shop owner’s perspective, any Chinese that shows up in that rural and remote area, is there to visit the Bethune House, which I’d say that he’s 99.9999% correct.

What such story has anything to do with this github repo? Well, let me reveal it in the end, but first let me explain why I need to ask my questions -- two folds:

- Being a computer programmer, who is obsessed with version controlling everything, I had been looking for a plain text music notation for decades. I had almost settled with the ABC notation when I happened to stumble upon jianpu-ly, which I hadn’t imagined that such a thing would exist before. So now I am very curious why such a wonderful program ever exists. So I started to look up who Mr. Silas S. Brown is, but
- Unlike youngsters nowadays who post everything about their lives on facebook, people in the computer world tend to leave as minimum digital footprint as possible. I’m like that and I found so is Mr. Silas S. Brown. Thus I want to interview him to satisfy my curiosity, to know more about him.

As put in his personal bio, Mr. Silas S. Brown is a [partially-sighted](http://ssb22.user.srcf.net/cvi.html) computer scientist at [Cambridge](http://ssb22.user.srcf.net/zhimo/) University in the UK, who come from West Dorset on the South-West peninsula of England. There isn’t much more personal information revealed in the English version of his self introduction, yet interestingly, he reveals himself much more in his [Chinese](http://ssb22.user.srcf.net/index-zh.html) version of self-introduction, from which we know that he involves with [剑桥大学中国文化促进协会](http://ssb22.user.srcf.net/old-ccs/) & [剑桥大学华乐团](http://ssb22.user.srcf.net/old-ccs/cucos.html), and he self teach himself Chinese, which is amazing giving Chinese is the most difficult language to learn in the world. 

I thought him to be an old professor but it turns out that he might be rather young, as he seems to be still attending Cambridge University in 1996 when he wrote [Clara Empricost](http://ssb22.user.srcf.net/clara/), but such a guess might be wrong.

So, now, finally, here are my interview questions (please don’t decline):

- Please identify if there is anything wrong with the above guess work.
- You seem to have learned Chinese by self teaching, with the help of [gradint, a program for self-study of foreign languages](http://ssb22.user.srcf.net/gradint/)[](http://ssb22.user.srcf.net/old-ccs/cucos.html), that you co-authorized, is that so?
- How long did it take you to learn Chinese, and since what age did you start?
- Why are you interested in learning Chinese, and are there many Chinese friends around you?
- The [jianpu-ly](https://github.com/ssb22/jianpu-ly) seems to be instigated by your [五线谱和盲文音乐软件](http://ssb22.user.srcf.net/mwrhome/)[](http://ssb22.user.srcf.net/old-ccs/cucos.html), but still, 
- why jianpu? Why not the staff, or ABC notation or anything?
- What are the challenges when you’re doing the jianpu-ly programming? It must be hard for any partially-sighted person.
- Your eyes’ situation seems to have gone worse, and you’re now [legally blind](https://github.com/ssb22/jianpu-ly/issues/18). Is it so or the situation hasn’t developed much.
- May I know if you are born with the eye problem please? It must be very hard for anyone, let alone going to the universities, and being a professor.

I have many more questions but so far for now, as I’m afraid that they’ll be declined. For reasons behind all above, including my above story, I just think the world deserves to know better about the inventor and author of the [jianpu-ly](https://github.com/ssb22/jianpu-ly) program, especially when jianpu is invented by a French / Genevan [Jean-Jacques Rousseau](https://en.wikipedia.org/wiki/Jean-Jacques_Rousseau), and it is only common/popular in East Asia, including Myanmar(Burma), [Japan](https://en.wikipedia.org/wiki/Japan), [Mainland China](https://en.wikipedia.org/wiki/Mainland_China) including [Taiwan](https://en.wikipedia.org/wiki/Taiwan), and not a single person from those area cares enough to write such a helpful program.

**Comment by ssb22** [comment]
Hi, you're right my [home page](http://ssb22.user.srcf.net/) needs more work.  I have a [full site index](http://ssb22.user.srcf.net/site-index.html) but it's 166 pages so far & harder to navigate, so I guessed the home page had better have just a few basic links (like the most important software I've done), and link to the full index at the bottom.  The Chinese version of my homepage has a slightly different set of links: it prioritizes things that I've translated into Chinese and/or done in connection with Chinese.  Both the English and the Chinese versions of the homepage are basically slightly different subsets of the full site index (which I've also [done in Chinese](http://ssb22.user.srcf.net/site-index-zh.html): I haven't yet managed to translate all the pages it links to, but at least the titles are there).

You might be interested in [梦姐's interview of me](http://ssb22.user.srcf.net/transcript.html).  My condition is from birth, but it was misdiagnosed until 1993 when I was 15 years old.  (My eyes are OK but the brain is not talking with them correctly.  So basically a kind of brain damage.)

A lot changed in 1993.  We finally knew what was wrong with me and what to do about it.  I was given access to specialist magnification equipment and other help, trained to use a cane for navigation (finally I could confidently walk down a street without having to follow a wall), didn't have to see psychotherapists any more, and moved to more appropriate schooling.  My family bought a PC and a friend got us a C++ compiler (I joined [ACCU](https://accu.org) the following year) and I started working on a music program.  (I had programmed school computers before, but this was going up a level.)

Then from 1995 to 1997 I did the final two years of my schooling at a [specialist school for the blind in Worcester](https://www.ncw.co.uk/) and that's where I did the automatic composition experiment.  (I recently talked about this at an English section of the Oxford China forum, [here is the video](https://www.youtube.com/watch?t=11056&v=aLMpbvh5udQ); I'm hoping they will release a version with the Q&A included because the audience had some good questions.)

Then in 1997 I started my undergraduate degree at Cambridge, where I started to meet East Asian international students for the first time.

At that time, I had to use computers in Cambridge that were still running Windows 3 and Netscape 2, which tended to crash or mess things up whenever I tried to change the size and colours (as I needed to do for my condition).  So I wrote my [Web Access Gateway](http://ssb22.user.srcf.net/access/) to fix that.  Then I discovered that the East Asian students were unable to read emails from their parents because the university was refusing to install East Asian fonts (they said they didn't want to risk installing anything not required by a course), and I thought "I can fix this: I've got an access gateway" and added a feature to show hanzi etc as pictures, which made me hugely popular with the Chinese and Japanese students (although the Koreans were not interested; maybe they all had their own computers).  Eventually, an actual Chinese Studies lecturer started using it, and then I knew what I had to do: help her write a letter to the computing service explaining that East Asian fonts and input methods are indeed required by a course, so please install them properly.  They did, my server traffic fell to zero and I became a nobody again (but I'd done the right thing).

(I'm hoping that jianpu-ly will follow the same pattern.  Once the core Lilypond developers realize jianpu is important, and integrate it properly into Lilypond itself, we won't need my add-on script anymore, at least not for new scores that don't already use it.  It's a transitory fix.)

One of my Chinese classmates wanted to start a Chinese club and [we started one](http://ssb22.user.srcf.net/old-ccs/).  I'd been involved in the computer society etc so I knew a bit about how to do student clubs, so I helped.  Their first website ran on my server along with the Access Gateway.  (Now it's all done on WeChat and I'm not sure how it works anymore, but I still say hi to them when I can.)  And later I [encouraged some Chinese students to start a 华乐团](http://ssb22.user.srcf.net/old-ccs/cucos.html) and I play flute with them sometimes.

I'm [not a professor](http://ssb22.user.srcf.net/papers/lecturing.html) (perhaps I got too involved in helping Chinese people instead) but not to worry.

I met my wife when I was translating a talk from English into Chinese for a local group.  I asked if she'd like to take over translating, which unnerved her a bit but I showed her how I was using [Wenlin](https://wenlin.com/) to help, which she found interesting and we started to keep in touch.  When we eventually married, we had [terrible trouble getting her a UK visa](http://ssb22.user.srcf.net/law/visa.html) but got there in the end.  The first version of jianpu-ly was originally written to print a hymnal for her father, as he wanted to sing in a group in Hong Kong that was using 5-line music he couldn't read.  (Unfortunately I made quite a few copying mistakes, but his friend gave my version to their leadership and they thought it was a good idea and published their own official corrected version.  They didn't use jianpu-ly to do it though; I'm not sure what they used.)  I was hoping jianpu-ly would also be useful for our local Chinese orchestra, but they haven't used it much, just occasionally for a yangqin part or something if their Xunscore printouts are particularly difficult to read (but sometimes they just write things by hand).  Perhaps they'll use it more in the future.

There are still quite a number of Chinese people in Cambridge and in the UK and many of them still treat me as a friend (well occasionally they [throw virtual knives at me](http://ssb22.user.srcf.net/law/cleaver.html) but mostly we're good), which is nice.

**Comment by suntong** [comment]
Ah, it's so refreshing and dearing to read what you write, and the linked contents too.

> I have a full site index but it's 166 pages so far & harder to navigate

Haha, I digged some of my "findings" from there, and apparently I'm missing quite a lot, :)

 梦姐's interview really touches me, and I'd like to quote a few paragraphs, 

> In November 2021 a Master’s student who uses the Internet name “Dream” wanted to interview me to encourage disabled friends back home not to give up. . . the resulting video was viewed by hundreds of thousands of people
> 
> Title: story of a visually-impaired person who finished Cambridge’s Computer Science degree
> . . .
> Dream: After chatting with Silas it’s hard to express my feelings, seems to be tough and pure, he was visually impaired from birth and bullied, misdiagnosed, sent to a special school and tried to take his life but still chose to do good and help others as far as he could, I hope his life runs well

this part really touches me, and then I read this:

> He hasn’t seen trees, sunlight, rain or snow and hasn’t even seen the face of a Chinese person. ​In the Western environment he probably heard many smears against China, but he can still choose to go and help those international students he’s never seen with his eyes, noble soul.

This comment is not just a hollow compliment. Take a look at [this](http://ssb22.user.srcf.net/papers/lecturing.html)

> I was invited to apply for a new lectureship at Manchester that specifically wanted what I’d worked on—but by this time I’d become involved in helping Cambridge’s local Chinese immigrants so much that I was worried what would happen to them if I left Cambridge for Manchester. 我在剑桥一两学院的研究员候选名单但进不去了，然后被邀请申请曼城的讲师任务，那时曼城特别对我的研究感兴趣。不过，那时候我也已经开始帮助剑桥的华人，我恐怕我离开剑桥去曼城也许使那些华人更困境，所以我留下了。

Indeed, noble soul!!

And lastly, 

> I'm hoping that jianpu-ly will follow the same pattern. Once the core Lilypond developers realize jianpu is important, and integrate it properly into Lilypond itself, we won't need my add-on script anymore . . . 

No! Being a computer programmer, who is obsessed with version controlling everything, I firmly believe that jianpu-ly has it is place as a plain text music notation tool, and I'll be continue using and advocating it.

Thanks for all your answers,

Cheers & Best Regards,
