### ISSUE TITLE
Sliding down symbol

### ISSUE THREAD

**Issue by suntong** [ssb22/jianpu-ly#43]
Trying to find a lilypond single word code/commands for the "sliding down symbol" which looks like a downward bending curved arrow,  symbolizing that the note should not keep steady when singing, but will be sliding down at the end. 

I wasn't able to find it myself. Is there such lilypond code, ie, can jianpu-ly produce a symbol like this? thx.

**Comment by ssb22** [comment]
The hardest part will be getting the symbol right.  We can either do it in Unicode or do it in Postscript.

The closest Unicode characters I can find are ⤴ for bend up and ⤵ for bend down (U+2934 and U+2935), but their appearance depends on the font (in some fonts the arrow head is bigger than the line, which is not so good).  If we can find a font that always gets them near enough, and if this font is likely to be installed on the system of whoever's running it, then it might work to put one of these characters after the note.

But really I think doing it in Postscript is more likely to be the way, as that will let us completely customise how it looks (length of line before it bends, size of arrow head, whether we want a full arrow head or only half of one, etc).  But writing that Postscript correctly is going to be harder than the Postscript I wrote for the 3 tremolo lines.  I'm hoping we can do the curved part with Postscript's "arc" command, because Bezier curves are harder to get right.  It might help if we can get a few examples of how different publishers in China print these things.

**Comment by suntong** [comment]
Oh, wow, if that's the case. Then let's just forget it. Thanks for looking into it. 

Looking at the _"hardest part"_, I think it causes way too much trouble to implement it, while there are other ways to convey the same idea. 

Thanks again for checking and hope that  my message reach you soon enough before you begin.
