### ISSUE TITLE
About the repeating

### ISSUE THREAD

**Issue by suntong** [ssb22/jianpu-ly#48]
Happy Mid Autumn @ssb22 first of all, 中秋快乐！

About the repeating, I saw there is _"Da capo"_:

`1 1 Fine 1 1 1 1 1 1 DC`

However, how to use it got me confused, as I thought that `Fine` should be put at the end, and `DC` means  repeating _'from the beginning'_. 

For "small repeat", there is another one [_"Dal Segno"_](https://en.wikisource.org/wiki/A_Dictionary_of_Music_and_Musicians/Da_Capo), i.e., `D.S.`, which is more oftenly used, and the repeating is from the ![image](https://github.com/ssb22/jianpu-ly/assets/422244/d852829d-0626-465a-b17f-f4d747656f58) symbol.

The segno sign is encoded in the Musical Symbols block of Unicode as U+1D10B 𝄋 MUSICAL SYMBOL SEGNO.[[4]](https://en.wikipedia.org/wiki/Dal_segno#cite_note-4). However, my system/browser is not able to display it.

**Comment by ssb22** [comment]
Yes `Fine` is at the end, but when there's a "DC al Fine", the end is not the last thing written.  E.g.:

    1 2 3 4 5 4 3 2 1 - - - Fine
    6 5 4 6 5 4 3 5 4 3 2 1 2 - - - DC

plays 1 2 3 4 5 4 3 2 1 - - - 6 5 4 6 5 4 3 5 4 3 2 1 2 - - - 1 2 3 4 5 4 3 2 1 - - -

In music there's also "DS al Fine" which is when you have a segno instead of going back to the very beginning, plus there are "DC al Coda" and "DS al Coda" which are versions of these two that instead of having "Fine" have an instruction to jump back past the "D* al coda" to a "coda" section at the very end.  I've not yet done jianpu-ly shortcuts for these as I've not yet encountered a piece that requires them in jianpu, but it's possible to put the Lilypond code in `LP:` blocks (search [this Lilypond documentation page](https://lilypond.org/doc/v2.23/Documentation/notation/long-repeats) for "segno")

**Comment by suntong** [comment]
Oh, thanks for the explanation. 

I've encountered a piece that requires "Dal Segno", i.e., D.S., but looking at the  Lilypond documentation page for "segno" you provided, I realized that it is far more complicated than I thought to get it right. 

So I'll do note above and note below instead. thanks.
