### ISSUE TITLE
How are nested slurs indicated?

### ISSUE THREAD

**Issue by zonewave** [ssb22/jianpu-ly#66]
I want the following effect  
![image](https://github.com/user-attachments/assets/16edfb97-8df1-4d4d-872b-95b50f7d69f1)

I tried to write like this, but only the outermost slur is displayed  
```jp

2 3  4  (  5  (  5 ) )
```

**Comment by ssb22** [comment]
That's not a nested slur, it's a tie inside a slur.  There are 3 reasons why it's important to tell Lilypond that the tie is a tie not a slur:

1. In professional music printing, ties are printed slightly differently from slurs (the curvature is slightly less),
2. In the MIDI output we want the note to be held over and not repeated,
3. If we later add lyrics, we want the tied note to count as just one word.

Use `~` for ties, or use `-` instead of the second `5` (jianpu-ly knows to change `-` after a barline into a repeat of the number with a tie)

**Comment by ssb22** [comment]
so it's `q1 q1 ~ 1 s6, ( s1 ) q2 s2 ( s3 ) s4 s5 ~ 5 - q0 s5 ( s6 q5 ) s5 ( s3 )` etc

**Comment by zonewave** [comment]
I see. Now I can write it like this
```jp
q1 q1 ~ 1 s6, ( s1 ) q2 s2 ( s3 ) s4 ( s5 ~ 5 ) - q0 s5 ( s6 q5 ) s5 ( s3 )
```

it can ok;
![image](https://github.com/user-attachments/assets/4955b1ac-a24a-44a8-8c3b-6af84cc92c4b)

**Comment by ssb22** [comment]
太好了

**Comment by unbored** [comment]
> I see. Now I can write it like this
> 
> ```
> q1 q1 ~ 1 s6, ( s1 ) q2 s2 ( s3 ) s4 ( s5 ~ 5 ) - q0 s5 ( s6 q5 ) s5 ( s3 )
> ```
> 
> it can ok; ![image](https://private-user-images.githubusercontent.com/26363539/390360788-4955b1ac-a24a-44a8-8c3b-6af84cc92c4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NTU0NTksIm5iZiI6MTczMjc1NTE1OSwicGF0aCI6Ii8yNjM2MzUzOS8zOTAzNjA3ODgtNDk1NWIxYWMtYTI0YS00NGE4LThjM2ItNmFmODRjYzkyYzRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDAwNTIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyY2QwNTE3MTA0YTZiYzY0Y2YyNTVhZmViMzcxOTI0Yzg1MjFjNzc5ZTIzNTUxMWU0NTQwNzA4NDczOGMwMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FafIgZE5YG8UpYt28_OeQQJnM1WT0TRebA7PpyWYNHY)

It looks like you’re using a previous version of the script? I saw the flipped beams and serif font
