### ISSUE TITLE
multiple consecutive grace notes?

### ISSUE THREAD

**Issue by RamKromberg** [ssb22/jianpu-ly#7]
I've been trying to convert jianpu sheets to western starting with an easy piece from http://www.qupu123.com/jipu/p341510.html but I'm not sure how to do multiple consecutive grace notes (in the last bar):

```
title=紫竹调
1=C 2/4
WithStaff

q1. s,6 q5 q3
s2 s3 s2 s1 2
q3 s3 s5 q5 q,6
q1'. s2' s7 s6 q5
6 -

\break

q5. ( s6 ) q1' ( q2' )
q6 ( q5 ) g[5] 3
q5 ( q2 ) q3 ( q5 )
q5 ( 1. )
q3 q5 q3 g[3] 5q

\break

s2 ( s3 s2 s1 ) g[s1 s,6] q1

```

It's heavily used in more advanced pieces like http://www.qupu123.com/qiyue/dixiao/gusuhang.html . 

While I'm at it, how do you do parenthesis like the ones in the first 5 bars intro from the first example?

Also, the 2nd example has some (Chinese? flute?) articulations I'm not familiar with nor do I know their western counterparts so if you do I'd appreciate a hint ;)

**Comment by ssb22** [comment]
Hi, sorry if this wasn't clear from the help text, but `g[s1 s,6]` won't work for 2 reasons:
1. the grace-note code expects a single word with no spaces, but you put a space between the grace notes,
2. the grace-note code expects to get just numbers, not note lengths.
So that one should be `g[1,6]` (which you can also write as `g[16,]` to make it clearer that the `,` applies to the second note).

jianpu-ly currently has no built-in support for parentheses in the music line.  That example you found is the first time I've seen them.  But you can tell Lilypond to skip 20 notes before the lyrics start by adding `\repeat unfold 20 { \skip 1 }` at the start of the `L:` or `H:` line.  We might be able to get the actual parentheses in by giving Lilypond some kind of `-\markup` command but I'm not sure (we'd be asking it to add extra symbols inline with the music, rather than around the music).  But at least setting it without the parentheses but with the lyrics starting in the right place would be a good start.

I'm afraid I don't know what all the articulations are in the gusuhang example.  I might be able to ask someone in a few months' time if [CUCOS](http://ssb22.user.srcf.net/old-ccs/cucos.html) starts up again; at the moment we're all in lockdown and the students are home.

**Comment by ssb22** [comment]
Thanks for the link to the LSR example.  Unfortunately it's not at all obvious how I can get this to work in the Jianpu line.  Oh well....
